export * from "@/pages/dashboard/home";
// export * from "@/pages/dashboard/profile";
// export * from "@/pages/dashboard/tables";
export * from "@/pages/dashboard/users";
export * from "@/pages/dashboard/Coaches";
export * from "@/pages/dashboard/EditUsers";
export * from "@/pages/dashboard/AddUsers";
export * from "@/pages/dashboard/AddCoaches";
export * from "@/pages/dashboard/EditPitche";
export * from "@/pages/dashboard/Purchases";
// export * from "@/pages/dashboard/notifications";
